name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login
        enable-AzPSSession: true # optional

    - name: Deploy Azure Functions
      uses: Azure/functions-action@v1.1.4
      with:
        # Name of the Azure Function App
        app-name: func-app-ltm
        # Function app slot to be deploy to
        slot-name: Production # optional
